// <auto-generated />
using System;
using BookingClone.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BookingClone.Migrations
{
    [DbContext(typeof(BookingCloneContext))]
    partial class BookingCloneContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BookingClone.Models.Agency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Commission")
                        .HasColumnType("decimal(4,2)");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<DateTime?>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Agencies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Commission = 15.00m,
                            CreatedAt = new DateTime(2019, 8, 26, 12, 11, 30, 380, DateTimeKind.Utc).AddTicks(881),
                            IsDeleted = false,
                            Name = "Todoric"
                        },
                        new
                        {
                            Id = 2,
                            Commission = 20.00m,
                            CreatedAt = new DateTime(2019, 8, 26, 12, 11, 30, 380, DateTimeKind.Utc).AddTicks(1972),
                            IsDeleted = false,
                            Name = "Airbnb"
                        },
                        new
                        {
                            Id = 3,
                            Commission = 23.00m,
                            CreatedAt = new DateTime(2019, 8, 26, 12, 11, 30, 380, DateTimeKind.Utc).AddTicks(1982),
                            IsDeleted = false,
                            Name = "Booking"
                        },
                        new
                        {
                            Id = 4,
                            Commission = 17.50m,
                            CreatedAt = new DateTime(2019, 8, 26, 12, 11, 30, 380, DateTimeKind.Utc).AddTicks(1983),
                            IsDeleted = false,
                            Name = "Trivago"
                        });
                });

            modelBuilder.Entity("BookingClone.Models.AuthUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccessFailedCount");

                    b.Property<DateTime?>("Birthdate");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Gender");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("LastName");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            Birthdate = new DateTime(1987, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConcurrencyStamp = "96ff1693-c0e4-4541-8621-8a47ab6708b4",
                            Email = "radekoncar@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Rade",
                            Gender = "M",
                            LastName = "Končar",
                            LockoutEnabled = false,
                            PhoneNumber = "0917453456",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            Birthdate = new DateTime(1982, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConcurrencyStamp = "b2a97872-e7e5-4e5c-95fa-f172c537ac2c",
                            Email = "antemastelic@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Ante",
                            Gender = "M",
                            LastName = "Mastelić",
                            LockoutEnabled = false,
                            PhoneNumber = "0924567484",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            Birthdate = new DateTime(1991, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConcurrencyStamp = "393a428f-60cb-43d1-aa3f-e275226bede7",
                            Email = "miadimsic@hotmail.com",
                            EmailConfirmed = false,
                            FirstName = "Mia",
                            Gender = "F",
                            LastName = "Dimšić",
                            LockoutEnabled = false,
                            PhoneNumber = "0959375035",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = 4,
                            AccessFailedCount = 0,
                            Birthdate = new DateTime(1982, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConcurrencyStamp = "a0cc1402-1242-48b2-bdb5-26fa3a346c53",
                            Email = "hrvojehorvat@hotmail.com",
                            EmailConfirmed = false,
                            FirstName = "Hrvoje",
                            Gender = "M",
                            LastName = "Horvat",
                            LockoutEnabled = false,
                            PhoneNumber = "0983765905",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false
                        });
                });

            modelBuilder.Entity("BookingClone.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AgencyId");

                    b.Property<DateTime>("CheckIn");

                    b.Property<DateTime>("CheckOut");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<bool>("IsDeleted");

                    b.Property<int?>("PaymentId");

                    b.Property<int>("RoomId");

                    b.Property<DateTime?>("UpdatedAt");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("AgencyId");

                    b.HasIndex("PaymentId");

                    b.HasIndex("RoomId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgencyId = 1,
                            CheckIn = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOut = new DateTime(2019, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2019, 8, 26, 12, 11, 30, 384, DateTimeKind.Utc).AddTicks(2484),
                            IsDeleted = false,
                            RoomId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            AgencyId = 2,
                            CheckIn = new DateTime(2019, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOut = new DateTime(2019, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2019, 8, 26, 12, 11, 30, 384, DateTimeKind.Utc).AddTicks(3901),
                            IsDeleted = false,
                            RoomId = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            AgencyId = 3,
                            CheckIn = new DateTime(2019, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOut = new DateTime(2019, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2019, 8, 26, 12, 11, 30, 384, DateTimeKind.Utc).AddTicks(3937),
                            IsDeleted = false,
                            RoomId = 3,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            AgencyId = 4,
                            CheckIn = new DateTime(2019, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOut = new DateTime(2019, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2019, 8, 26, 12, 11, 30, 384, DateTimeKind.Utc).AddTicks(3944),
                            IsDeleted = false,
                            RoomId = 4,
                            UserId = 4
                        });
                });

            modelBuilder.Entity("BookingClone.Models.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("PhoneNumber");

                    b.Property<DateTime?>("UpdatedAt");

                    b.Property<string>("WebAddress")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Ulica Izidora Kršnjavog 1",
                            CreatedAt = new DateTime(2019, 8, 26, 12, 11, 30, 380, DateTimeKind.Utc).AddTicks(6747),
                            IsDeleted = false,
                            Name = "Westin",
                            PhoneNumber = "38514892000",
                            WebAddress = "www.westinzagreb.com"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Miramarska Cesta 24",
                            CreatedAt = new DateTime(2019, 8, 26, 12, 11, 30, 380, DateTimeKind.Utc).AddTicks(7802),
                            IsDeleted = false,
                            Name = "International",
                            PhoneNumber = "38516108800",
                            WebAddress = "www.hotel-international.hr"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Trg Krešimira Ćosića 9",
                            CreatedAt = new DateTime(2019, 8, 26, 12, 11, 30, 380, DateTimeKind.Utc).AddTicks(7816),
                            IsDeleted = false,
                            Name = "Esplanade",
                            PhoneNumber = "38514566600",
                            WebAddress = "www.esplanade.hr"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Trg Josipa Jurja Strossmayera 10",
                            CreatedAt = new DateTime(2019, 8, 26, 12, 11, 30, 380, DateTimeKind.Utc).AddTicks(7817),
                            IsDeleted = false,
                            Name = "Palace",
                            PhoneNumber = "38514899600",
                            WebAddress = "www.palace.hr"
                        });
                });

            modelBuilder.Entity("BookingClone.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AgencyId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime?>("UpdatedAt");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("AgencyId");

                    b.HasIndex("UserId");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgencyId = 1,
                            CreatedAt = new DateTime(2019, 8, 26, 12, 11, 30, 384, DateTimeKind.Utc).AddTicks(7602),
                            IsDeleted = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            AgencyId = 2,
                            CreatedAt = new DateTime(2019, 8, 26, 12, 11, 30, 384, DateTimeKind.Utc).AddTicks(8190),
                            IsDeleted = false,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            AgencyId = 3,
                            CreatedAt = new DateTime(2019, 8, 26, 12, 11, 30, 384, DateTimeKind.Utc).AddTicks(8199),
                            IsDeleted = false,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            AgencyId = 4,
                            CreatedAt = new DateTime(2019, 8, 26, 12, 11, 30, 384, DateTimeKind.Utc).AddTicks(8201),
                            IsDeleted = false,
                            UserId = 4
                        });
                });

            modelBuilder.Entity("BookingClone.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("HotelId");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("NumberOfBeds");

                    b.Property<decimal>("PricePerNight")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(5);

                    b.Property<decimal>("Size")
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("Type")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2019, 8, 26, 12, 11, 30, 382, DateTimeKind.Utc).AddTicks(958),
                            HotelId = 1,
                            IsDeleted = false,
                            NumberOfBeds = 2,
                            PricePerNight = 100.00m,
                            RoomNumber = "101",
                            Size = 34.42m,
                            Type = "Double"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2019, 8, 26, 12, 11, 30, 382, DateTimeKind.Utc).AddTicks(2843),
                            HotelId = 2,
                            IsDeleted = false,
                            NumberOfBeds = 2,
                            PricePerNight = 200.00m,
                            RoomNumber = "202",
                            Size = 42.12m,
                            Type = "Suite"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2019, 8, 26, 12, 11, 30, 382, DateTimeKind.Utc).AddTicks(2865),
                            HotelId = 3,
                            IsDeleted = false,
                            NumberOfBeds = 4,
                            PricePerNight = 300.00m,
                            RoomNumber = "301",
                            Size = 54.66m,
                            Type = "Quad"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2019, 8, 26, 12, 11, 30, 382, DateTimeKind.Utc).AddTicks(2866),
                            HotelId = 4,
                            IsDeleted = false,
                            NumberOfBeds = 4,
                            PricePerNight = 400.00m,
                            RoomNumber = "202",
                            Size = 73.81m,
                            Type = "Executive"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2019, 8, 26, 12, 11, 30, 382, DateTimeKind.Utc).AddTicks(2867),
                            HotelId = 1,
                            IsDeleted = false,
                            NumberOfBeds = 2,
                            PricePerNight = 100.00m,
                            RoomNumber = "102",
                            Size = 34.42m,
                            Type = "Double"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2019, 8, 26, 12, 11, 30, 382, DateTimeKind.Utc).AddTicks(2869),
                            HotelId = 2,
                            IsDeleted = false,
                            NumberOfBeds = 2,
                            PricePerNight = 200.00m,
                            RoomNumber = "204",
                            Size = 42.12m,
                            Type = "Suite"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2019, 8, 26, 12, 11, 30, 382, DateTimeKind.Utc).AddTicks(2870),
                            HotelId = 3,
                            IsDeleted = false,
                            NumberOfBeds = 4,
                            PricePerNight = 300.00m,
                            RoomNumber = "304",
                            Size = 54.66m,
                            Type = "Quad"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2019, 8, 26, 12, 11, 30, 382, DateTimeKind.Utc).AddTicks(2874),
                            HotelId = 4,
                            IsDeleted = false,
                            NumberOfBeds = 4,
                            PricePerNight = 400.00m,
                            RoomNumber = "206",
                            Size = 73.81m,
                            Type = "Executive"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2019, 8, 26, 12, 11, 30, 382, DateTimeKind.Utc).AddTicks(2875),
                            HotelId = 1,
                            IsDeleted = false,
                            NumberOfBeds = 2,
                            PricePerNight = 100.00m,
                            RoomNumber = "103",
                            Size = 34.42m,
                            Type = "Double"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2019, 8, 26, 12, 11, 30, 382, DateTimeKind.Utc).AddTicks(2876),
                            HotelId = 2,
                            IsDeleted = false,
                            NumberOfBeds = 2,
                            PricePerNight = 200.00m,
                            RoomNumber = "206",
                            Size = 42.12m,
                            Type = "Suite"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2019, 8, 26, 12, 11, 30, 382, DateTimeKind.Utc).AddTicks(2877),
                            HotelId = 3,
                            IsDeleted = false,
                            NumberOfBeds = 4,
                            PricePerNight = 300.00m,
                            RoomNumber = "305",
                            Size = 54.66m,
                            Type = "Quad"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2019, 8, 26, 12, 11, 30, 382, DateTimeKind.Utc).AddTicks(2878),
                            HotelId = 4,
                            IsDeleted = false,
                            NumberOfBeds = 4,
                            PricePerNight = 400.00m,
                            RoomNumber = "208",
                            Size = 73.81m,
                            Type = "Executive"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<int>("RoleId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<int>("UserId");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<int>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("BookingClone.Models.Booking", b =>
                {
                    b.HasOne("BookingClone.Models.Agency", "Agency")
                        .WithMany("Bookings")
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BookingClone.Models.Payment")
                        .WithMany("Bookings")
                        .HasForeignKey("PaymentId");

                    b.HasOne("BookingClone.Models.Room", "Room")
                        .WithMany("Bookings")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BookingClone.Models.AuthUser", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("BookingClone.Models.Payment", b =>
                {
                    b.HasOne("BookingClone.Models.Agency", "Agency")
                        .WithMany()
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BookingClone.Models.AuthUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("BookingClone.Models.Room", b =>
                {
                    b.HasOne("BookingClone.Models.Hotel", "Hotel")
                        .WithMany("Rooms")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("BookingClone.Models.AuthUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("BookingClone.Models.AuthUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BookingClone.Models.AuthUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("BookingClone.Models.AuthUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
